{{- if .Values.environment }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hrx-chatbot.fullname" . }}-env
  labels:
    {{- include "hrx-chatbot.labels" . | nindent 4 }}
data:
{{- range $k, $v := .Values.environment }}
  {{ $k }}: {{ $v | toString | quote }}
{{- end }}
{{- end }}
