apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hrx-chatbot.fullname" . }}
  labels:
    {{- include "hrx-chatbot.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hrx-chatbot.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hrx-chatbot.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: hrx-chatbot
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          {{- if or .Values.environment (hasKey . "dummy") }}
          envFrom:
            {{- if .Values.environment }}
            - configMapRef:
                name: "{{ include "hrx-chatbot.fullname" . }}-env"
            {{- end }}
            - secretRef:
                name: "hrx-chatbot-env"   # fixed & simple
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
