apiVersion: v1
kind: Secret
metadata:
    name: hrx-chatbot-env
    namespace: staging
type: Opaque
stringData:
    # Environment variables for development
    HRX_BASE_URL:   "https://api-staging-monolithic-b2b.hrxbd.org"

    REPORT_DIR: "/tmp"

    # Application Settings
    APP_SECRET_KEY: "jWEMUgH4L8OV2PjQPyT-vkYEsVmxnLwFiligLvx3oIg="
    APP_DATABASE_URL:  postgresql://hrx_user:hrx_db_pass@pgbouncer-face-recog.hrx.svc.cluster.local:6432/postgres



    # Celery Configurations
    CELERY_BROKER_URL: redis://redis-master:6379
    CELERY_RESULT_BACKEND: redis://redis-master:6379

    # Cache Configurations
    CACHE_TTL_SECONDS: "3600"


    # Consul Configurations
    USE_CONSUL: "true"
    CONSUL_HOST: consul
    CONSUL_PORT: "8500"
    CONSUL_PREFIX: hrx-chatbot

    # Google Gemini API Key
    #GOOGLE_API_KEY="AIzaSyA1AkSh-vRk4msSa9R4Pv7kyp9goeQa_vk"
    GOOGLE_API_KEY: "AIzaSyCGR-unzUQjwP6I6GD5J3kiAaoABFCt9UQ"
    GEMINI_TOP_P: "0.9"
    GEMINI_TOP_K: "40"
    GEMINI_TEMPERATURE: "0.1"
    GEMINI_RETRY_DELAY: "5"
    GEMINI_MAX_RETRIES: "3"
    # Gemini Standard Configurations
    GEMINI_MAX_TOKENS: "12000"
    GEMINI_TIMEOUT: "60"
    # Gemini Extended Configurations (for complex operations like Tax, CV, Personalized Journey)
    GEMINI_MAX_TOKENS_EXTENDED: "12000"
    GEMINI_TIMEOUT_EXTENDED: "120"



    # Embedding / Model configuration
    EMBEDDING_MODEL: all-MiniLM-L6-v2
    LANGUAGE_MODEL: gemini-3.1-pro-preview