{{- if .Values.environmentSecrets }}
{{- $fullName := include "pmx-backend.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-env
  labels:
  {{- include "pmx-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.environmentSecrets }}
  {{ $key }}: {{ $value | toString | b64enc | quote }}
  {{- end }}
{{- end }}
